on: 
  workflow_dispatch:
    
  push:
    branches:
      - main

name: Azure ARM
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      env:
        SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./main.bicep
        parameters: adminPasswordOrKey=$SSH_PUBLIC_KEY
        failOnStdErr: false